apiVersion: batch/v1
kind: Job
metadata: 
  name: busybox
spec:
  template:
    spec:
      containers:
      - name: busybox_sleep
        image: busybox
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 3