apiVersion: batch/v1
kind: Job
metadata: 
  name: busybox
spec:
  template:
    spec:
      containers:
      - name: busybox
        command: ["sleep", "2"]
      restartPolicy: Never
  backoffLimit: 3